### ISSUE TITLE
Cannot find module '../lib/index'

### ISSUE THREAD

**Issue by arlac77** [andreyvit/plist-to-json#2]
plist-to-json -h

module.js:340
    throw err;
          ^
Error: Cannot find module '../lib/index'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/plist-to-json/bin/plist-to-json.js:2:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)

**Comment by andreyvit** [comment]
Oops, looks like a publication error. One sec...

**Comment by andreyvit** [comment]
Please try again, should work.

**Comment by arlac77** [comment]
works fine now - thanks
